org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=false
org.gradle.caching=true

# Mod metadata
mod.version=0.1.0
mod.group=dev.adrian
mod.id=chest-tracker
mod.name=ChestTracker

# Shared deps
deps.fabric_loader=0.19.5

# Per-version, overridden in versions/<id>/gradle.properties
deps.fabric_api=[VERSIONED]
mod.java=[VERSIONED]
mod.mc_dep=[VERSIONED]
