package dev.adrian.chesttracker.core.model;

/**
 * How a container came to exist.
 *
 * <p>{@link #UNKNOWN} is a first-class answer, not a failure. A client attached
 * to a vanilla server receives no structure data and no placement history, so
 * almost everything it sees is genuinely unclassifiable. Surfacing that beats
 * guessing.
 */
public enum Origin {
    /** Generated by worldgen: inside a structure, or still holding an unrolled loot table. */
    NATURAL,
    /** Observed being placed by a player. */
    PLAYER_PLACED,
    /** No evidence either way. */
    UNKNOWN;

    /**
     * Combines an existing classification with a newly observed one, keeping
     * whichever rests on stronger evidence.
     *
     * <p>Observed placement outranks everything: if we watched a player put a
     * chest down inside a village, it is theirs regardless of the structure
     * bounding box it happens to sit in. {@code UNKNOWN} never overwrites a
     * real answer, so a later scan that cannot classify a container will not
     * erase what an earlier one established.
     */
    public Origin merge(Origin observed) {
        if (observed == PLAYER_PLACED) return PLAYER_PLACED;
        if (this == PLAYER_PLACED) return PLAYER_PLACED;
        if (observed == NATURAL || this == NATURAL) return NATURAL;
        return UNKNOWN;
    }
}
